services:
  frontend:
    image: ghcr.io/swipemytalent/frontend:${GIT_COMMIT_HASH:-latest}
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      - "traefik.http.routers.web.rule=Host(`swipemytalent.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.middlewares=rate-limit"
      - "traefik.http.middlewares.rate-limit.rateLimit.average=50"
      - "traefik.http.middlewares.rate-limit.rateLimit.burst=100"
    depends_on:
      - backend

  backend:
    image: ghcr.io/swipemytalent/backend:${GIT_COMMIT_HASH:-latest}
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    secrets:
      - jwt
      - db-password
      - db-name
      - db-user
    environment:
      - NODE_ENV=prod
      - JWT_KEY_FILE=/run/secrets/jwt
      - POSTGRES_DB_FILE=/run/secrets/db-name
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_USER_FILE=/run/secrets/db-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    depends_on:
      - postgres
  
  postgres:
    image: postgres:17-alpine
    secrets:
      - db-password
      - db-name
      - db-user
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db-name
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_USER_FILE=/run/secrets/db-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    configs:
      - source: init-sql
        target: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - pg-data:/var/lib/postgresql/data/

  
  reverse-proxy:
    image: traefik:v3.4.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sduviviertech@outlook.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

configs:
  init-sql:
    file: ./backend/db/migration/init.sql

volumes:
  pg-data:
  letsencrypt:

secrets:
  db-password:
    external: true
  db-name:
    external: true
  db-user:
    external: true
  jwt:
    external: true